[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "paris"    # Shanghai will be tested in the CI.
auto_detect_solc = false
optimizer = true
optimizer_runs = 1_000
gas_limit = 100_000_000  # ETH is 30M, but we use a higher value.

# Deploy
[rpc_endpoints]
metis_sepolia = "https://sepolia.metisdevops.link"

[etherscan]
