[profile.default]
solc_version = "0.8.27"
src = 'contracts'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]
verbosity = 4
ffi = true
ast = true
build_info = true
extra_output = ['storageLayout']

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"
metis_sepolia = "https://sepolia.metisdevops.link"

[fmt]
multiline_func_header = "params_first"
line_length = 80
tab_width = 2
quote_style = "double"
bracket_spacing = true
int_types = "long"
